name: django_env
channels:
  - defaults
  - conda-forge
dependencies:
 - django=3.0
 - faker
 - numpy
 - pillow
 - python==3.8
 - bcrypt
 - argon2_cffi
 - django-bootstrap4
 - beautifulsoup4
 - misaka
 - django-braces
 - django-debug-toolbar 
