# Generated by Django 3.0.3 on 2020-05-18 01:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='create_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 5, 18, 1, 16, 6, 980159, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='create_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 5, 18, 1, 16, 6, 957629, tzinfo=utc)),
        ),
    ]
